# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.11
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: walksanator
book_id: hexcasting:thehexbook
default_branch: main
github_repo: hexsky
gradle_mod_version_key: mod_version
hexdoc_mod_plugin_classname: HexskyModPlugin
hexdoc_plugin_classname: HexskyPlugin
java_lang:
    ext: kt
    src: kotlin
java_package: net/walksanator/hexsky
mod_display_name: Hexxy Skies
modid: hexsky
multiloader: true
package_export_root: doc/src/hexdoc_hexsky/_export
package_name: hexdoc-hexsky
package_slug: hexdoc_hexsky
package_src: doc/src/hexdoc_hexsky
pages_url: https://walksanator.github.io/hexsky/
pattern_regex:
    per_world_value: 'true'
    regex: make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)
pattern_registry: casting/patterns/PatternRegistry.kt
